[package]
name = "qmx-capture"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
cpal = "0.15"
anyhow = "1.0"
rustfft = "6.1"
crossterm = "0.27"
textplots = "0.8"

[badges]
maintenance = { status = "as-is" }
